/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d0d54a5c-0384-407d-823f-27c59ec7fb3f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4jvpD5R8A",
    "aws_user_pools_web_client_id": "700o8n1977q3vbo79c1dmv60h0",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://cazw14vs00.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
